[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/who-is-gary"
  to = "/who-is-gary/"
  status = 301

[[redirects]]
  from = "/the-issues"
  to = "/the-issues/"
  status = 301

[[redirects]]
  from = "/supporters"
  to = "/endorsements/"
  status = 301

[[redirects]]
  from = "/contact"
  to = "/contact/"
  status = 301

[[redirects]]
  from = "/media"
  to = "/media/"
  status = 301

[[redirects]]
  from = "/media/media-archive"
  to = "/media/"
  status = 301

[[redirects]]
  from = "/links-resources"
  to = "/media/"
  status = 301

[[redirects]]
  from = "/endorse-volunteer"
  to = "/support/"
  status = 301